AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  turborepo-remote-cache-lambda

  Sample SAM Template for turborepo-remote-cache-lambda

Parameters:
  JWTSecret:
    Type: String
    Description: JWT secret for authenticating requests
  S3Bucket:
    Type: String
    Description: S3 bucket for storing the remote cache

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  TurboRepoRemoteCacheFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          JWT_SECRET: !Ref JWTSecret
          S3_BUCKET: !Ref S3Bucket
      Events:
        TurboRepoRemoteCache:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{paths+}
            Method: any
        TurboRepoRemoteCacheRoot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: any
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External: ['@aws-sdk/*']
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TurboRepoRemoteCacheApi:
    Description: API Gateway endpoint URL for Prod stage for Turbo Repo Remote Cache function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  TurboRepoRemoteCacheFunction:
    Description: Turbo Repo Remote Cache Lambda Function ARN
    Value: !GetAtt TurboRepoRemoteCacheFunction.Arn
  TurboRepoRemoteCacheFunctionIamRole:
    Description: Implicit IAM Role created for Turbo Repo Remote Cache function
    Value: !GetAtt TurboRepoRemoteCacheFunctionRole.Arn
